algoritmo "contar1a10Para"

var
  cont: inteiro
inicio

//      Para cont <- 1 ate 10 faca
//             Escreval (cont)
 //     FimPara
 
 //      Para cont <- 5 ate 10 faca
//             Escreval (cont)
 //     FimPara
 
 //      Para cont <- 1 ate 10 passo 2  faca
//             Escreval (cont)
 //     FimPara
 
   Para cont <- 10 ate 1 passo -1  faca
        Escreval (cont)
   FimPara
fimalgoritmo
