algoritmo "conversor"
// Função :
// Autor :
// Data : 23/01/2022
// Seção de Declarações 
var
   //A: inteiro
   //A:real
   angulo, Seno: real
inicio
// Seção de Comandos 
   //A <- Abs(-50)
   //A <- Exp(5,2)
   //A <- RaizQ(81)
   //A <- Int(RaizQ(155))

   Escreva("Informe um angulo: ")
   Leia(angulo)
   Seno <- Sen(GraupRad(angulo))
   Escreva("O seno de",angulo," e igual a", Seno)
fimalgoritmo
